### ISSUE TITLE
pyimagesearch-22-minutes-to-2nd-place.ipynb having a issue in reshape the array

### ISSUE THREAD

**Issue by haritha91** [jrosebr1/microsoft-dsvm#1]
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>()

ValueError: cannot reshape array of size 3211264 into shape (32,2048)`

The issue is with reshaping the feature array.

**Comment by jrosebr1** [comment]
What version of Keras are you using?

**Comment by haritha91** [comment]
It's 2.1.2

**Comment by jrosebr1** [comment]
In between Keras versions the output dimensions of the final volume changed (I believe this was a bug fix of some sort). To fix it, just change:

`features = features.reshape((features.shape[0], 2048))`

To:

`features = features.reshape((features.shape[0], 2048 * 7 * 7))`
